baseURL = 'https://tech.sevdesk.com'
languageCode = 'en-us'
title = 'sevDesk Tech Blog'
theme = "ananke"

[params]
  site_logo = "img/sevdesk-logo-inverted.svg"
  show_reading_time = true
  background_color_class = "bg-gray"